// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxaoygzeqmvwlkamlohu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4YW95Z3plcW12d2xrYW1sb2h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2ODAxODIsImV4cCI6MjA2MzI1NjE4Mn0.sae9dAL6wl8D5CZW_0_p2V1b6ONlXOvZsnNx5ebeHV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);